# Site settings
title: Functional Programming at the University of Kansas
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"
exclude: ['_meta','dist','ku-fpg-github-io.cabal','Shake.hs','BibTeX.hs','.cabal-sandbox']
